spring:
  application:
    name: materialized-view
  kafka:
    consumer:
      group-id: materialized-view-1
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:ORCL2
    username: SCOTT
    password: tiger
    driver-class-name: oracle.jdbc.driver.OracleDriver

customer:
  destination:
    mv-genral-publish:
      topic: mv1-lookup
    mv-merge-publish:
      topic: mv1-mereg-pub-topic
